version: '2.1'

services:
    server:
        build:
            context: docker
            dockerfile: Dockerfile-lab3
        privileged: true
        volumes:
            - ..:/elocal
        tty: true
        cap_add:
          - NET_ADMIN
          - NET_RAW
          - SYS_ADMIN
        networks:
            net:
              ipv4_address: 198.12.0.14
        depends_on:
            - "router"
    middle:
        build:
            context: docker
            dockerfile: Dockerfile-lab3
        volumes:
            - ..:/elocal
        tty: true
        cap_add:
          - NET_ADMIN
          - NET_RAW
          - SYS_ADMIN
        networks:
            net:
              ipv4_address: 198.12.0.15
        depends_on:
            - "router"
        sysctls:
          - net.ipv4.ip_forward=1
    router:
        build:
            context: docker
            dockerfile: Dockerfile-lab3
        volumes:
            - ..:/elocal
        tty: true
        cap_add:
          - NET_ADMIN
          - NET_RAW
          - SYS_ADMIN
        networks:
            dmz:
              ipv4_address: 172.11.0.1
            net:
              ipv4_address: 198.12.0.1
        sysctls:
          - net.ipv4.ip_forward=1
        #command: bash -c "tc qdisc add dev eth0 root netem loss 50% && tc qdisc add dev eth1 root netem loss 50% && sleep infinity"
    client:
        build:
            context: docker
            dockerfile: Dockerfile-lab3
        volumes:
            - ..:/elocal
        tty: true
        cap_add:
          - NET_ADMIN
          - NET_RAW
          - SYS_ADMIN
        networks:
            dmz:
              ipv4_address: 172.11.0.14
        depends_on:
            - "router"
            - "server"
networks:
    dmz:
        ipam:
            driver: default
            config:
                - subnet: 172.11.0.0/16
                  gateway: 172.11.0.1
    net:
        ipam:
            driver: default
            config:
                - subnet: 198.12.0.0/16
                  gateway: 198.12.0.1
